version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Install Serverless framework
      - npm install -g serverless
    

  pre_build:
    commands:
      # Configure AWS CLI with environment variables
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region us-west-2 

  build:
    commands:
      # Deploy Serverless application
      - serverless deploy  


