Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyQueue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - MyDLQ
            - Arn
        maxReceiveCount: 3 # Number of retries before moving to DLQ

  MyDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyDLQ

  SqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: MyQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource:
              Fn::GetAtt:
                - MyQueue
                - Arn
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: MyTopic
