Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyQueue

  SqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: MyQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource:
              Fn::GetAtt:
                - MyQueue
                - Arn
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: MyTopic
